mkdir Bit_Tables/
mkdir Bit_Tables/Tables_INP/
mkdir Bit_Tables/Tables_A00/
mkdir Bit_Tables/Tables_A01/
mkdir Bit_Tables/Tables_A02/
mkdir Bit_Tables/Tables_A03/
mkdir Bit_Tables/Tables_B00/
mkdir Bit_Tables/Tables_B01/
mkdir Bit_Tables/Tables_B02/
mkdir Bit_Tables/Tables_B03/
mkdir Bit_Tables/Tables_C00/
mkdir Bit_Tables/Tables_C01/
mkdir Bit_Tables/Tables_C02/
mkdir Bit_Tables/Tables_C03/
mkdir Bit_Tables/Tables_D00/
mkdir Bit_Tables/Tables_D01/
mkdir Bit_Tables/Tables_D02/
mkdir Bit_Tables/Tables_D03/
unzip ../../0002_detection/Code_extract_ics/ics_original_010.zip
unzip ../../0003_training/template_profiling_bytes/templateLDA_O010.zip 
unzip ../get_answers/answer_bit.zip
